### ISSUE TITLE
Analyze StackTrace for convert to CodeMap

### ISSUE THREAD

**Issue by Behzadkhosravifar** [Behzadkhosravifar/ErrorControlSystem#33]
In __ErrorControlSystem__ when an unhandled exception occur then show a message to user for present error information. In __Developer__ UI mode if the application run on IDE , so message show code maps for developer user to help more than on normal error massage.

**Comment by Behzadkhosravifar** [comment]
For example, StackTrace Context:

```StackTrace
at TestExpStackTraceSet.Form1..ctor() in d:\TestExpStackTraceSet\TestExpStackTraceSet\Form1.cs:line 28
   at TestExpStackTraceSet.Program.Main() in d:\TestExpStackTraceSet\TestExpStackTraceSet\Program.cs:line 19
```

Developer UI Message same this:

Codes | File (Line, Column)
-------- | -------------
TestExpStackTraceSet -> Form1 -> .ctor() | [File Path](d:\TestExpStackTraceSet\TestExpStackTraceSet\Form1.cs) (28, 26)
TestExpStackTraceSet -> Program -> Main() | [File Path](d:\TestExpStackTraceSet\TestExpStackTraceSet\Program.cs) (19, 10)
... | ...

**Comment by Behzadkhosravifar** [comment]
-    ._____   ____________.
-    |_____|-|____________|
    -                  |
    -                  |
    -            | ____     _____________.
    -            |_____|-|_____________|
        -                                       |
        -                                       |
        -                                 | ____   _____________.
        -                                 |_____|-|_____________|

**Comment by Behzadkhosravifar** [comment]
In ErrorControlSystem any DeveloperUI message have this feature now.
